//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTasis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public int ID { get; set; }
        public Nullable<long> No_Rekening { get; set; }
        public System.DateTime Tanggal { get; set; }
        public long Setoran { get; set; }
        public long Penarikan { get; set; }
        public Nullable<long> Saldo { get; set; }
    
        public virtual Siswa Siswa { get; set; }
    }
}
